---
- hosts: db

  tasks:
  - name: Print all facts
    ansible.builtin.debug:
      msg: >
        The defualt IPv4 address of {{ ansible_facts.fqdn }}
        is {{ ansible_facts.default_ipv4.address }}
      