---
- hosts: db

  tasks:
    - name: restat rsyslog
      ansible.builtin.service:
        name: "rsyslog"
        state: restarted
      notify:
        - print msg
  handlers:
    - name: print msg
      ansible.builtin.debug:
        msg: "rsyslog is restarted"