#SPDX-License-Identifier: MIT-0
---
# vars file for myrole.httpd

# RHEL
# httpd_service:
#   - httpd
#   - yum-utils
# repo_dir: /repo

# Ubuntu
httpd_service:
  - apache2-utils
  - apache2
repo_dir: /repo